### ISSUE TITLE
Problem with ws.audioscrobbler.com request

### ISSUE THREAD

**Issue by lduesing** [fdemmer/Picard-Last.fm.ng-Plugin#12]
Current git-picard and current picard-14 branch on current ubuntu wily:
E: 20:12:23 Network request error for https://ws.audioscrobbler.com:443/2.0/?album=Dark+Sky+Island&api_key=0a8b8f968b285654f9b4f16e8e33f2ee&method=album.gettoptags&artist=Enya: Error downloading https://ws.audioscrobbler.com:443/2.0/%3Falbum=Dark+Sky+Island&api_key=0a8b8f968b285654f9b4f16e8e33f2ee&method=album.gettoptags&artist=Enya - server replied: Not Found (QT code 203, HTTP code 404)

Seems URL-part "?" is getting encoded.

**Comment by fdemmer** [comment]
i don't think that is an error. the api simply signals that there are no tags using a http 404.

thanks for reporting though, maybe i'll change the logging severity or handle it nicer somehow.

**Comment by fdemmer** [comment]
confirmed. can reproduce with picard 1.4. something changed in picard 1.4.

**Comment by lduesing** [comment]
I'm not sure - but on first view: picard/webservice.py: 
XmlWebService:_start_request there is a parameter queryargs, which is not used by your code, but should.

**Comment by fdemmer** [comment]
> but should

it's not as easy as that. that parameter does not exist in Picard 1.3

**Comment by fdemmer** [comment]
fixed in v0.14

**Comment by lduesing** [comment]
Thanks a lot. Works like a charm!
