### ISSUE TITLE
No issue as of yet, just a thanks :)

### ISSUE THREAD

**Issue by Rouzax** [fdemmer/Picard-Last.fm.ng-Plugin#24]
I've always used the old LastFM plus plugin which doesn't work anymore. Just wanted to say thanks for creating this :+1:

**Comment by fdemmer** [comment]
thanks guys! :tada:

**Comment by Rouzax** [comment]
@fdemmer: Are you planning more releases for this plugin?

**Comment by fdemmer** [comment]
don't have time in the foreseeable future. if you want to submit a pull request i'll try to find time to review. feel free to fork too. any specific feature missing or pressing issue?

**Comment by skelliam** [comment]
I also want to say thanks.  

I created my config.ini with the following lines:

[global]
lastfm_key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[category-defaults]
; used to join tags if >1 are to be used (None to use multtag)
separator = ";"

The separator ";" is recommended here:
http://www.blisshq.com/music-library-management-blog/2011/03/12/multiple-genres-in-mp3s/

But the author notes that there doesn't seem to really be a standard, only recommendations.

Anyway thanks for this it is working great for me!
