### ISSUE TITLE
Crash when loading large release

### ISSUE THREAD

**Issue by JamiBradley** [fdemmer/Picard-Last.fm.ng-Plugin#27]
Whenever I try to load the large release below (29 CDs), it runs fine to start but after a few minutes the memory starts increasing rapidly until Picard crashes.  If I disable this plugin, the release loads fine.

This was both with 0.13 and 0.14 of the plugin.  I am using Picard 1.4.0dev5 (win_20160312) but I have seen it with older versions as well.

http://musicbrainz.org/release/3dfdef45-4f3c-3db7-9313-b1bfacc6b189

**Comment by fdemmer** [comment]
this is a known issue. thanks for reporting this with a great example to do more testing though! :+1:

as i usually do not tag more than a hand full of (small) albums at once, this has never been a problem for me and therefore is not a priority to fix, but at least on other user reported crashes.

i have gone into detail about the whys and hows in #20

i don't have time to rewrite the problematic parts in the foreseeable future. pull requests are very welcome though!

**Comment by JamiBradley** [comment]
Thanks - I don't know how I missed [https://github.com/fdemmer/Picard-Last.fm.ng-Plugin/issues/20].  If I get some free time, I might try to understand it better, but I'll need to learn Python first!
