### ISSUE TITLE
config.ini

### ISSUE THREAD

**Issue by MichaelTiebesl** [fdemmer/Picard-Last.fm.ng-Plugin#28]
How to create a config.ini file?
Is it just a copy from defaults.ini, and then change the settings I want?
Or do I write in the config.ini file only what i wanna change from the defaults.ini?

For example, I want to change only a few genre from the [searchlist] in defaults.ini.
Do I make a copy from defaults.ini and called it config.ini and change the genre what I ?

Thanks

**Comment by fdemmer** [comment]
default will always be loaded before config, so just creating a config with the things to override works.

however values in config overwrite the whole value of defaults (not merging or adding). so best copy the whole searchlist initially and then modify.

**Comment by MichaelTiebesl** [comment]
Thank you so much for your time. I know it now for sure and after a few testing, it works for me. :)
