### ISSUE TITLE
[Windows 10] Not sure what I'm doing wrong, but the plugin doing anything

### ISSUE THREAD

**Issue by Jock924491** [fdemmer/Picard-Last.fm.ng-Plugin#30]
Followed directions in installation guide. I copied the files into the plugins directory, added a lastfm.ini with personal key, started picard, added a few random albums and no genre data was added.
#### Environment and versions
- Operating system: Windows 10
- Picard version(s): 1.3.2
- Plugin version(s) or commit hash: .14 & master were both tried
#### Suggestions, ideas, thoughts, code, ...

Since most people are not having this problem, should I have an additional program installed?
Here are a few albums I've using: 
http://musicbrainz.org/release/d147dce9-31ce-4775-9af4-1d451d2f9c05?tport=8000
http://musicbrainz.org/release/a2de224a-4f10-30fa-8df3-d4fcf77aab61?tport=8000
http://musicbrainz.org/release/2d5d5d4c-d0d7-4772-962f-de7185605ff8?tport=8000

**Comment by fdemmer** [comment]
i cannot reproduce the issue. do you see any exceptions/errors/stacktraces in picard's "Help" - "View Error/Debug Log"?

**Comment by kshitizarora** [comment]
Hello Sir, 
I am also on windows 10 and experiencing same issue even after clean installation on windows 10. The tags are left blank by the plugin please help as soon as possible.

I dont understand this but you can see for yourself if there is an error of plugin or anything else, submitting bugs reported by picard

E: 03:51:57 Plugin 'compat' : Traceback (most recent call last):
  File "picard\plugin.pyo", line 292, in load_plugin
  File "C:\Users\kshit\AppData\Roaming\MusicBrainz\Picard\plugins\compat.py", line 17, in <module>
ImportError: No module named vendor.ConfigParser

W: 03:51:57 Module 'featartist' conflict: unregistering previously loaded 'Feat. Artists Removed' version 0.2 from 'C:\Program Files (x86)\MusicBrainz Picard\plugins\featartist.py'
W: 03:51:57 Plugin 'logging' from 'C:\Users\kshit\AppData\Roaming\MusicBrainz\Picard\plugins\logging.py' is not compatible with this version of Picard.
E: 03:51:57 Plugin 'mixins' : Traceback (most recent call last):
  File "picard\plugin.pyo", line 292, in load_plugin
  File "C:\Users\kshit\AppData\Roaming\MusicBrainz\Picard\plugins\mixins.py", line 9, in <module>
ImportError: cannot import name settings

E: 03:51:57 Plugin 'plugin' : Traceback (most recent call last):
  File "picard\plugin.pyo", line 292, in load_plugin
  File "C:\Users\kshit\AppData\Roaming\MusicBrainz\Picard\plugins\plugin.py", line 13, in <module>
ImportError: cannot import name settings

W: 03:51:57 Plugin 'script' from 'C:\Users\kshit\AppData\Roaming\MusicBrainz\Picard\plugins\script.py' is not compatible with this version of Picard.
E: 03:51:57 Plugin 'settings' : Traceback (most recent call last):
  File "picard\plugin.pyo", line 292, in load_plugin
  File "C:\Users\kshit\AppData\Roaming\MusicBrainz\Picard\plugins\settings.py", line 8, in <module>
ImportError: No module named helpers.searchlists

E: 03:52:46 Network request error for http://musicbrainz.org:80/ws/2/release/ad908ccd-8ea2-4b26-ba55-91fb4a8258d3?inc=release-groups+media+recordings+artist-credits+artists+aliases+labels+isrcs+collections+artist-rels+release-rels+url-rels+recording-rels+work-rels: Error downloading http://musicbrainz.org:80/ws/2/release/ad908ccd-8ea2-4b26-ba55-91fb4a8258d3?inc=release-groups+media+recordings+artist-credits+artists+aliases+labels+isrcs+collections+artist-rels+release-rels+url-rels+recording-rels+work-rels - server replied: Service Temporarily Unavailable (QT code 301, HTTP code 200)
E: 03:52:46 Error downloading http://musicbrainz.org:80/ws/2/release/ad908ccd-8ea2-4b26-ba55-91fb4a8258d3?inc=release-groups+media+recordings+artist-credits+artists+aliases+labels+isrcs+collections+artist-rels+release-rels+url-rels+recording-rels+work-rels - server replied: Service Temporarily Unavailable

Thank You.

**Comment by fdemmer** [comment]
this:

> File "C:\Users\kshit\AppData\Roaming\MusicBrainz\Picard\plugins\compat.py", line 17, in
> ImportError: No module named vendor.ConfigParser

... indicates you have not installed the plugin correctly. you should preserve the `lastfmng` directory when extracting the files in the plugins directory. so `compat.py` should be in `C:\Users\kshit\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\compat.py`
