### ISSUE TITLE
Last.fm.ng not grabbing top genre

### ISSUE THREAD

**Issue by Gitouisl** [fdemmer/Picard-Last.fm.ng-Plugin#33]
It seems that within the last couple months, the plugin is grabbing one of the top genres from Last.fm, but not the top one, if the top one is the left-most genre in the list on the artist's page. Maybe Last/fm changed the weight system?

For example, Ministry will get Industrial as the 1 genre tag which I've set the ini file to pull, rather than Industrial Metal.
#### Environment and versions
- Operating system: Windows 10
- Picard version(s): 1.3.2, as well as the nightlies
- Plugin version(s) or commit hash: the most current one
#### How to reproduce the problem

Run a release in Picard, the top (left-most) artist genre from Last.fm most likely won't be the one that makes it into the genre tag if tag is limited to one genre as I have.

I am assuming the left-most genre tag on Last.fm is the top tag, but maybe I'm incorrect? It seems to be that way just from browsing through artists. But I don't see anywhere you can get the weight scores, so I'm stumped. Hope this can be updated, thanks for the great plugin!

**Comment by GitrianDK** [comment]
It is because the genre from the Last.fm API is in a different order.

http://www.last.fm/music/Ministry

http://ws.audioscrobbler.com/2.0/?method=artist.gettoptags&artist=Ministry&api_key=68d35f1d326b4750c19767da5faf93af

**Comment by Gitouisl** [comment]
Alright, thanks for clearing that up! I'll just assume the tags on the artist page are in a random order and not worry about them anymore when pulling the tags with the plugin in Picard.

**Comment by fdemmer** [comment]
the `count` is relevant for ranking tags, not the sequence in the api response or on the website:

```
<tag><count>100</count><name>industrial</name><url>https://www.last.fm/tag/industrial</url></tag>
```
