### ISSUE TITLE
Weird tag results

### ISSUE THREAD

**Issue by Rouzax** [fdemmer/Picard-Last.fm.ng-Plugin#34]
Somehow the tags that are retrieved for some songs do not make sense.
#### Environment and versions
- Operating system: Windows 2012 R2
- Picard version(s): 1.4.0Dev5
- Plugin version(s) or commit hash: Latest git version
#### How to reproduce the problem

The song from Marco Borsato - Zij is returning weird genre tags that do not makes sense.
![image](https://cloud.githubusercontent.com/assets/4103090/19144360/5373402c-8ba9-11e6-9f6d-bba794c4fb64.png)
Last FM: http://www.last.fm/music/Marco+Borsato/_/Zij

**Comment by Rouzax** [comment]
Here is another one
Justin Bieber - Childeren
![image](https://cloud.githubusercontent.com/assets/4103090/19191412/99ca6d26-8ca2-11e6-88c6-cb633f53228f.png)
When I look in the logging I see that a vaild request is being done.

```
D: 15:30:22 Received reply for https://ws.audioscrobbler.com:443/2.0/?track=Children&api_key=0a8b8f968b285654f9b4f16e8e33f2ee&method=track.gettoptags&artist=Justin Bieber: HTTP 200 (OK) 
```

This is the response, no Black Metal in sight
![image](https://cloud.githubusercontent.com/assets/4103090/19191873/7d7a1750-8ca4-11e6-9afb-fc4f55e483f2.png)

**Comment by fdemmer** [comment]
here's the black metal:

```
I: 16:32:18 Last.fm.ng - >>> process track tags
I: 16:32:18 Last.fm.ng - grouping: 14 tag(s) before threshold filter:
I: 16:32:18 Last.fm.ng - grouping: pop (200), black metal (170), hip-hop (80), r&b (46), death metal (24), ...
I: 16:32:18 Last.fm.ng - grouping: score threshold: 100.0 (50%)
I: 16:32:18 Last.fm.ng - grouping: 2 tag(s) filtered:
I: 16:32:18 Last.fm.ng - grouping: pop (200), black metal (170)
I: 16:32:18 Last.fm.ng - grouping: overflow to genre: black metal (170)
I: 16:32:18 Last.fm.ng - grouping: metatag: grouping
I: 16:32:18 Last.fm.ng - grouping = Pop
I: 16:32:18 Last.fm.ng - genre: 14 tag(s) before threshold filter:
I: 16:32:18 Last.fm.ng - genre: dance pop (800), r&b (46), teen pop (18), rap (18), hardcore (8), ...
I: 16:32:18 Last.fm.ng - genre: score threshold: 320.0 (40%)
I: 16:32:18 Last.fm.ng - genre: 1 tag(s) filtered:
I: 16:32:18 Last.fm.ng - genre: dance pop (800)
I: 16:32:18 Last.fm.ng - genre: metatag: genre
I: 16:32:18 Last.fm.ng - genre = Black Metal; Dance Pop
```

it's a grouping tag being overflown to genre. so from logging output this looks ok.

from what api response this exactly came, i do not know... from the release id i see that this is the album you are tagging?
https://musicbrainz.org/release/6518bf9e-3032-4524-9422-3a825430dbc1

maybe it's a problem with compilations.

**Comment by Rouzax** [comment]
Yes that is the album I was testing with.
How are the grouping tags looked up?

**Comment by fdemmer** [comment]
Hi Rouzax, is this still a problem for you? Sorry, for not looking into it for _years_ :(

**Comment by Rouzax** [comment]
I don't think so but this is quite some time ago 😆 
EDIT:
Nope looks good now:
![image](https://user-images.githubusercontent.com/4103090/81813461-c3d4fc80-9527-11ea-8ca9-b3d9b8586a42.png)
