### ISSUE TITLE
How we can mix all the tags on genre 

### ISSUE THREAD

**Issue by ismaelnovo** [fdemmer/Picard-Last.fm.ng-Plugin#36]
Hi!

android phone players can't manage lot of id3 extended and personal tags. Is there a easy way to put all the collected tags and the calculated years (80's ; 90's ...) only in standard genre field? Not elegant but very functional and easy to implement.

Lot of thanks.

**Comment by duri2** [comment]
100% agreed. Is it possible?

**Comment by fdemmer** [comment]
you can probably write a picard script to combine/rewrite all the tags/information the plugin determined.

i'd also be happy to review a pr with that functionality. i am not likely to invest a lot more time in new feature development here, sorry.
