### ISSUE TITLE
Adding Occasion Tag to Genre

### ISSUE THREAD

**Issue by ZHANKODI** [fdemmer/Picard-Last.fm.ng-Plugin#37]
I have used the Occasion tag for occasions such as Christmas, Halloween, etc.

I currently have three genre tags which has worked great, but ideally, I would like to throw the Occasion tag, when it exists, as a 4th tag if possible.

Any ideas how this could be done?

**Comment by ZHANKODI** [comment]
If anyone is interested, I was able to resolve my issue by createing a new command called Affix.  Affix works like Prepend except is also add 1 to the limit.

If anyone is interested I can post my code changes.

**Comment by fdemmer** [comment]
if you want to contribute, open a pull request.
