### ISSUE TITLE
Can't write any tag

### ISSUE THREAD

**Issue by gdimopoulos** [fdemmer/Picard-Last.fm.ng-Plugin#38]
#### Environment and versions
* Operating system: Ubuntu 16.04 64-bit
* Picard version(s): 1.3.2
* Plugin version(s) or commit hash: 0.13

#### How to reproduce the problem
The plugin can download the tags from last.fm. 
I then save the file to write the new tag info.
When I reload the file, the albumgenre, albumgrouping, albumood, Mood tags are still empty.

Other tags get written without any issues. I tried with different files and permissions but nothing seems to work.

**Comment by fdemmer** [comment]
albumgenre, albumgrouping, albumood are not supported by id3, they are determined by the plugin to use in scripts or naming. see also: https://github.com/fdemmer/Picard-Last.fm.ng-Plugin#naming-rules

**Comment by gdimopoulos** [comment]
Thank you for the reply but I'm not sure I understood what you said or the link you sent. Apart from the tags you mentioned I reported problems with the Mood tag as well. Can you please elaborate a bit more about how to solve this problem? Thanks!
