### ISSUE TITLE
Existing tags are overwritten with "Unknown"

### ISSUE THREAD

**Issue by l-g** [fdemmer/Picard-Last.fm.ng-Plugin#39]
I just started using this plugin and after going through a couple of hundred tracks I realised that existing tags (genre, grouping) that made sense were overwritten with "Unknown". That doesn't make a lot of sense in my eyes? If I tagged something "classic" and that is replaced with "unknown" my situation is worse after using this plugin than before.

#### Environment and versions

OS X
Picard 1.3.2
Downloaded plugin last week

#### How to reproduce the problem

Here is an example

https://musicbrainz.org/release/61ca036a-edc2-410a-8414-015724759a4a

I had tagged it before I got this plugin and now Picard wants to replace the grouping tag with "Unknown".

#### Suggestions, ideas, thoughts, code, ...

I don't know if the source for Unknown is Last FM or the plugin but this keyword (and possibly others) should not be propagated, even if the field is empty but especially if the field has a value.

**Comment by fdemmer** [comment]
that can be configured, see https://github.com/fdemmer/Picard-Last.fm.ng-Plugin#configuration and set the `default_unknown` variable to nothing:

```
[global]
; string used as fallback, when no tag value could be determined
default_unknown = 
```

please report back if that works for you!

**Comment by l-g** [comment]
Thank you.
