### ISSUE TITLE
Picard 2.0 support

### ISSUE THREAD

**Issue by RyanThaDude** [fdemmer/Picard-Last.fm.ng-Plugin#40]
I'm curious since I'm currently testing the latest Picard 2.0 are you updating the plugin?

**Comment by fdemmer** [comment]
picard 2.0 was not on my radar, is there any documentation for api changes?

**Comment by RyanThaDude** [comment]
It's currently in development, 1.4.2 is still the stable version. I'm not sure if there's anything documented as of yet as I just recently starting working with the development builds on their GitHub. The major change seems to be the move from Python 2.7 to 3 (I'm building with 3.6). Some of my plugins from Picard 1.4 work just fine. Others, including Last.fm.ng fail to even load, even when adding 2.0 the API string in meta.py.

**Comment by fdemmer** [comment]
please try the 2.0 beta release: https://github.com/fdemmer/Picard-Last.fm.ng-Plugin/releases/tag/v2.0rc1

**Comment by RyanThaDude** [comment]
So far so good, working perfectly. Going to be testing it out more in the next day or so. Thanks!

**Comment by Enverex** [comment]
Doesn't look like this works anymore; It fails trying to import picard.mbxml and XmlWebService from picard.webservice.

EDIT: Looks like it's just named "WebService" now.

**Comment by Andy2244** [comment]
Yes imports changed to:
```
from picard.mbjson import (
    medium_to_metadata,
    track_to_metadata,
)
from picard.webservice import WebService as PluginXmlWebService
```
The internal containers also changed to dicts:
```
         #for medium_node in release_node.medium_list[0].medium:
         for medium_node in release_node['media']:
 
         #for track_node in medium_node.track_list[0].track:
             for track_node in medium_node['tracks']:
                #track = Track(track_node.recording[0].id, album)
                track = Track(track_node['recording']['id'], album)
```
It than crashes at:
```
        lfm = data.lfm.pop()
        if not lfm:
            log.warning("invalid response: 'lfm' tag missing", tagtype, query)
            return
```
'data' has no "lfm" member and thats where my quick fixing ended, since i have no reference on how this call should look like.

Maybe this can be updated to the latest picard 2.0 master?

**Comment by fdemmer** [comment]
please try the new pre-release. the switch to mbjson should now be complete: https://github.com/fdemmer/Picard-Last.fm.ng-Plugin/releases/tag/v2.0.0rc2

**Comment by fdemmer** [comment]
https://github.com/fdemmer/Picard-Last.fm.ng-Plugin/releases/tag/v2.0.0
