### ISSUE TITLE
No genre/mood/style provided for tracks with multiple artists

### ISSUE THREAD

**Issue by BustaUppa** [fdemmer/Picard-Last.fm.ng-Plugin#41]
I've started using this plugin with Picard.  It has been filling out the genre, style, and mood tags like I want it to.  However, I've noticed that tracks with multiple artists seem to trip it up.  On any track in which the "artists" tag is multi-value, the genre, mood, and style all show up as "Unknown."

I've seen this on several different albums, both "proper" artist albums and compilations (where it is more readily apparent, particularly with modern pop music).  It is apparent that the relative popularity of a track isn't an issue - for example, an artist album had all tags filled out, except for one track with "unknowns", which happened to be the one track on the album with a guest artist.

#### Environment and versions

* Operating system: Windows 10
* Picard version(s): 1.4.2
* Plugin version(s) or commit hash:  0.14

#### How to reproduce the problem

Run any album through Picard that contains at least one "collaboration" track (i.e. multiple artists or a "featured" artist)

**Comment by fdemmer** [comment]
please provide the exact musicbrainz release url you used to reproduce the issue.
