### ISSUE TITLE
Can't install 2.0rc1?

### ISSUE THREAD

**Issue by Soulsick** [fdemmer/Picard-Last.fm.ng-Plugin#44]
Hi,

I just updated my Picard to version 1.4.2 and also noticed you had new versions of your great and very helpful plugin. I downloaded both newer versions 0.15 and 2.0rc1. 0.15 works out of the box and Picard recognizes it, just like the 0.14 version I had installed earlier. But when I install 2.0 rc1, Picard doesn't recognize the plugin at all and log shows strings like this:

E: 13:44:35 Plugin 'lastfmng' : Traceback (most recent call last):
  File "picard\plugin.pyo", line 299, in load_plugin
  File "C:\Users\542216\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\__init__.py", line 64, in <module>
  File "C:\Users\542216\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 2, in <module>
  File "C:\Users\542216\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\logging.py", line 7, in <module>
AttributeError: 'module' object has no attribute 'Handler'

Am I doing something wrong, or what could it be?

**Comment by fdemmer** [comment]
as the [release notes](https://github.com/fdemmer/Picard-Last.fm.ng-Plugin/releases/tag/v2.0rc1) mention, the 2.x branch is only for picard 2.x

**Comment by Soulsick** [comment]
Thank you for your answer. I closed my issue, since I noticed it myself. I didn't even know such a developer version exists, that's why it took a moment to realize. Great job anyway, I really like your plugin and I'm glad someone continued, after the original plugins stopped working.
