### ISSUE TITLE
Still not working with PyQt5

### ISSUE THREAD

**Issue by ludovig** [fdemmer/Picard-Last.fm.ng-Plugin#48]
Hello,

Plugin last release still not working with pyqt5, at least on gentoo.
I had to fork https://github.com/ludovig/Picard-Last.fm.ng-Plugin, but I will not make pull request since I think qt network calls should be replaced by other libraries.

Thanks for the great plugin by the way !

**Comment by fdemmer** [comment]
thank you for your kind words and (almost) contribution! :)

the plugin will most probably continue to use picard's qt webservice infrastructure as it provides the throttling and parsing too. normally i'd use `requests` in standalone projects, but this is a plugin, that imho should use as much as the "host application's" code as possible.
