### ISSUE TITLE
City and Country

### ISSUE THREAD

**Issue by gjera** [fdemmer/Picard-Last.fm.ng-Plugin#5]
Hi

I think that City and Country Tag should be swapped if we want to have same befaviour as in LastFmPlus. (https://musicbrainz.org/doc/MusicBrainz_Picard/Documentation/Plugins/Lastfmplus)
So there should be change in 'settings.py'

---

```
        'country': 'comment:Songs-DB_Custom3',
        'city': 'comment:Songs-DB_Custom4',
```

---

**Comment by fdemmer** [comment]
makes sense on first look. it is not an easy change though, in the sense, that it changes the default behaviour of the plugin. i plan to move that settings out into config.ini at some point, so i think i'll wait until then to fix this. it should make it easier to setup the plugin the way you want.

**Comment by fdemmer** [comment]
in v0.10 you can configure the category to metatag assignment in your `config.ini`, eg:

```
[category-city]
limit = 1
threshold = 0.7
metatag_track = comment:Songs-DB_Custom4
```

i left the defaults unchanged for now. vote here if you really want the default to be changed.
