### ISSUE TITLE
Picard 2.0.1/win/osx: No module named 'configparser'

### ISSUE THREAD

**Issue by eddiestrike** [fdemmer/Picard-Last.fm.ng-Plugin#50]
No idea whatt's going on, but this plugin won't let me install it on the new Picard.

I saw you released a 2.0+ version some days ago, so thought it would work fine, but nope!

**Comment by fdemmer** [comment]
you need to provide more info than that.

how are you "installing" it? did you read/follow the instructions in the readme?

**Comment by eddiestrike** [comment]
I drop the lastfmng folder from the .rar into the plugin folder of the Picard plugin folder, then refresh. Worked perfectly for 1.4 but not for 2.0.1.

**Comment by fdemmer** [comment]
the releases are not provided as rar files. where do you get them from?

did you delete the old lastfmng folder first?

enable debug log output in "help - view error/debug log". are there any errors?

**Comment by eddiestrike** [comment]
I get them from the releases page on github.

v2.0.0rc2
Assets
 Source code (zip)

**Comment by eddiestrike** [comment]
Yes there is a lot of errors: https://pastebin.com/GfnnWqYu

**Comment by fdemmer** [comment]
that's the relevant one:

```
  File "C:\Users\eddiestrike\AppData\Local\MusicBrainz\Picard\plugins\lastfmng\settings.py", line 4, in <module>
    from configparser import ConfigParser, NoOptionError
ImportError: No module named 'configparser'
```

thanks!

all those other errors are what looks like picard 1.x plugins. [you probably should clean that up](https://blog.musicbrainz.org/2018/07/19/picard-2-0-released/#comment-145803).

**Comment by eddiestrike** [comment]
Ok, I deleted the old plugins and most of the errors cleared up.

**Comment by xdHampus** [comment]
I am also getting the same error code, but without all the additional ones @eddiestrike got related to other plugins.
Tested on a clean install of Picard 2.0.1
-EDIT
Tested on 2.0, as well, same error code.

**Comment by fdemmer** [comment]
also Windows?

Am 28. Juli 2018 11:27:20 MESZ schrieb Hampus <notifications@github.com>:

**Comment by Altheos** [comment]
Got the same problem on windows 10.
Grabbing official configparser.py and saving it into lastfm-ng plugin directory seems to fix errors, but Picard is crashing after.

**Comment by fdemmer** [comment]
just release 2.0.0 with configparser: https://github.com/fdemmer/Picard-Last.fm.ng-Plugin/releases/tag/v2.0.0
