### ISSUE TITLE
Unable to install 2.0.0rc2 on Picard Version 2.0.2 (osx_20180730121159)

### ISSUE THREAD

**Issue by tobsen987** [fdemmer/Picard-Last.fm.ng-Plugin#51]
I updated to Picard 2.0.2 today, downloaded 2.0.0rc2 of your plugin and put the 'lastfmng' folder in the plugin folder, restarted Picard several times but can't get the plugin to show in the plugin settings of Picard. Is there anything I am missing?

#### Environment and versions

* Operating system: macOS 10.13.6 (17G65)
* Picard version(s): 2.0.2 (osx_20180730121159)
* Plugin version(s) or commit hash: 2.0.0rc2

#### How to reproduce the problem

see above

**Comment by fdemmer** [comment]
please provide the error/debug log: go to `Help - View Error/Debug Log` and copy/paste into a pastebin (eg. https://hastebin.com); add the link here!

**Comment by tobsen987** [comment]
https://hastebin.com/votucudiro.sql

**Comment by fdemmer** [comment]
same as #50, thanks for the report!
