### ISSUE TITLE
Doesn't seem to work on Picard 2.1.3

### ISSUE THREAD

**Issue by kaysond** [fdemmer/Picard-Last.fm.ng-Plugin#54]
Just installed the latest plugin version fresh on Picard 2.1.3. I copied `defaults.ini` to `config.ini`. Unfortunately nothing seems to actually happen. I've tried a number of tracks via acoustid and tag lookup, but nothing gets populated to the grouping or genre tags.

Debug log show that the plugin is running, and there are no errors.

```
I: 11:39:32,392 /home/administrator/.config/MusicBrainz/Picard/plugins/lastfmng/settings.<module>:50: host: ws.audioscrobbler.com:443
I: 11:39:32,392 /home/administrator/.config/MusicBrainz/Picard/plugins/lastfmng/settings.<module>:51: key: 0a8b8f968b285654f9b4f16e8e33f2ee
I: 11:39:32,392 /home/administrator/.config/MusicBrainz/Picard/plugins/lastfmng/settings.<module>:55: collect_unused: False
I: 11:39:32,393 /home/administrator/.config/MusicBrainz/Picard/plugins/lastfmng/settings.<module>:57: ignore_feat_artists: False
I: 11:39:32,393 /home/administrator/.config/MusicBrainz/Picard/plugins/lastfmng/settings.<module>:59: default_unknown: Unknown
I: 11:39:32,395 /home/administrator/.config/MusicBrainz/Picard/plugins/lastfmng/settings.<module>:248: enabled categories: grouping (1), genre (4), mood (4), occasion (4), category (4), country (2), city (1), decade (1)
```

#### Environment and versions

* Operating system: Ubuntu 18.04.01
* Picard version(s): 2.1.3
* Plugin version(s) or commit hash: 2.0.1

**Comment by fdemmer** [comment]
I cannot reproduce the problem.

Please provide the MusicBrainz URL to the album you are trying to tag, that does not seem work (eg. https://musicbrainz.org/release/a6cf7274-0708-4c6a-b401-f6c42ccaafe5).

BTW: There is no need to _copy_ the settings files. You _can_ use a `config.ini` file to _override_ settings from `defaults.ini`. It is not necessary.

**Comment by kaysond** [comment]
I ended up wiping the whole musicbrainz config folder and reinstalled and now it works!
