### ISSUE TITLE
Can't 'enable it in the options dialog for plugins' as instructed

### ISSUE THREAD

**Issue by jackhulk** [fdemmer/Picard-Last.fm.ng-Plugin#55]
Hello

I've used this excellent plugin before, but haven't used MBP in a long while. Recently installed MBP v2.1.3 and this plugin v2.0.1 on Windows 10. Issue is I cannot 'enable it in the options dialog for plugins' as instructed.

I can confirm this plugin is in correct directory (~/.config/MusicBrainz/Picard/plugins/lastfmng/) so I'm not sure where I am going wrong here? Perhaps this plugin only works with MBP v2.0.1?Please let me know.

Many thanks

**Comment by fdemmer** [comment]
yes, it works with v2.1.3.

windows and macos/linux have different locations for configuration and plugins directory. are you sure, you installed it in the right place? you are giving conflicting information with "Windows 10" and that path. see: https://picard.musicbrainz.org/docs/faq/#config-location

check the log (Help - View Error/Debug Log) if the plugin is being loaded (look for something containing "... lastfmng/settings ...").

**Comment by jackhulk** [comment]
Hi again fdemmer! Great to see you are still developing this great plugin, thank you!

Discovered from the log that there was an issue with my edit of defaults.ini (updated genre/mood etc). Tried with original defaults.ini and now MBP is able to see and enable the plugin, however, it still doesn't appear to be working. None of formally populated tags such as albumgenre, albumgrouping, albummood are being scrapped....

![MBP](https://user-images.githubusercontent.com/32033854/54534271-e602d700-4983-11e9-969f-a3a45fc561c6.JPG)

As above, the plugin is untouched now, no edits, exactly as it comes originally. Can confirm there are no errors showing in log.

Where am I going wrong please?

**Comment by fdemmer** [comment]
i tried to reproduce with this [release](https://musicbrainz.org/release/462abddd-1dd7-4867-b2f2-3f76f4e4cf87) and get various genre/grouping tags:

![MusicBrainzPicard_20190318_01](https://user-images.githubusercontent.com/630975/54558339-c38daf80-49bd-11e9-8b27-e4f898ceafc4.png)

sorry, there are no leads i can follow to debug this for you.
