### ISSUE TITLE
Possible intermittent memory leak looking up obscure tracks in large albums

### ISSUE THREAD

**Issue by limb-trimmer** [fdemmer/Picard-Last.fm.ng-Plugin#59]
Possible intermittent memory leak looking up obscure tracks in large albums.

#### Environment and versions

* Operating system: OSX 10.13
* Picard version(s): 2.1.3
* Plugin version(s) or commit hash: 2.0.4

#### How to reproduce the problem

1) enable last.fm.ng plugin
2) look up a HUGE "album", which is probably not well represented in the last.fm database, e.g. [https://musicbrainz.org/release/ac989b56-4d7f-49f8-a7a1-db905de8e7a0](https://musicbrainz.org/release/ac989b56-4d7f-49f8-a7a1-db905de8e7a0)
3) log indicates a lot of requests are being met with server error 400
4) wait an hour or so, and watch as plugin may gradually consume all of 32GB of RAM, and starts to need disk caching

screenshot:
![Screen Shot 2019-06-28 at 3 09 27 PM](https://user-images.githubusercontent.com/52330537/60368717-380dbc80-99b7-11e9-8bbf-81686b310144.png)

**Comment by fdemmer** [comment]
thank you for your report, this is a known issue: #20
