### ISSUE TITLE
Plugin not appearing in XP or Vista: "ImportError: No module named urllib"

### ISSUE THREAD

**Issue by HennyPenny** [fdemmer/Picard-Last.fm.ng-Plugin#6]
Thanks for your work on this plugin.

picard.exe.log (Vista log extract below, XP log almost identical)
E: 21:30:31 Plugin 'lastfmng' : Traceback (most recent call last):
  File "picard\plugin.pyo", line 191, in load_plugin
  File "C:\Users\Emma\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng__init__.py", line 62, in <module>
  File "C:\Users\Emma\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 5, in <module>
ImportError: No module named urllib

Using Picard-Last.fm.ng-Plugin-master.zip downloaded 16/10/2015

**Comment by fdemmer** [comment]
thanks, regression from 6be8c348d47fbf7013f95383918a63b776ecb7e9, 0.8 should be ok

**Comment by fdemmer** [comment]
@HennyPenny what picard version?

**Comment by HennyPenny** [comment]
**@dfemmer** Picard 1.3.2
lastfmng 0.8 works on Vista (and I assume XP)
However LastFM appears to be very troubled. 
New API keys are not currently available. 
After clicking in circles for some time I found this tucked away on the support forum among posts by unhappy users.
https://getsatisfaction.com/lastfm/topics/the-api-home-page-always-redirects-me-to-the-home-page
_"Laura Last.fm, Official Rep
51 Posts 30 Reply Likes 
Hi all,
API key registration isn't available at the moment. Sorry about that.
The API pages you're currently seeing are a static snapshot of our old website, with the API key registration and management functionalities not being available there. ... "_
This leaves the API key included in lastfmng as the only key available to new users of your plugin.

**Comment by fdemmer** [comment]
fixed in v0.9.1
