### ISSUE TITLE
Does not work with Picard 2.2.x

### ISSUE THREAD

**Issue by ghost** [fdemmer/Picard-Last.fm.ng-Plugin#60]
Sadly, the current plugin works only up to Picard version 2.1.3.  I tried with the newer versions -- 2.2, 2.2.1 and 2.2.2 -- and all failed to load the plugin.

#### Environment and versions

* Operating system: Windows10
* Picard version(s): 2.2.2
* Plugin version(s) or commit hash: 2.0.4

**Comment by fdemmer** [comment]
thank you for your report!

it works for me:

![2019-10-17 11_47_43-Window](https://user-images.githubusercontent.com/630975/66998581-c9bf4800-f0d4-11e9-8055-d5565006ce82.png)
![2019-10-17 11_54_26-Options](https://user-images.githubusercontent.com/630975/66998645-e8254380-f0d4-11e9-93a2-037a58aac89a.png)


as i cannot reproduce the problem please provide more info on what errors you get: 

- go to **Help - View Error/Debug Log** 
- on the bottom left set verbosity to **Info** (or **Debug**)
- find lines containing "lastfmng" that look like errors and post them here

**Comment by ghost** [comment]
Hi Florian,,
Thank you for the lightning fast response! And thanks for pointing me to the error log menu (I’m not used to reporting errors!).
Fantastic plugin by the way.  I downloaded the top 3000 tags from lastfm and am in the process of sorting them.  I’ll gladly share my finished work.

Previously I had all the files (Picard-Last.fm.ng-Plugin-2.0.4.zip as well as its unzipped directory, the rezipped lastfmng directory and its unzipped version) in the plugin directory. Never had a problem as I simply selected the lastfmng.zip I had created.  It appears now that MM 2.2.x autoloads all the plugins in the directory (not just the ones you had activated or selected) – so that was creating conflicts.  I therefore removed all the files there, reinstalled MM 2.2.2 and redownloaded your plugin just to ensure there wasn’t anything amiss with the files I had.

Here’s the log when I selected lastfmng.zip (file contains a directory lastfmng) – see attached:



D: 13:43:13,999 tagger.__init__:209: Starting Picard from 'C:\\Program Files\\MusicBrainz Picard\\picard\\tagger.pyc'

D: 13:43:13,999 tagger.__init__:211: Platform: Windows-10-10.0.18362-SP0 CPython 3.7.4

D: 13:43:13,999 tagger.__init__:212: Versions: Picard 2.2.2, Python 3.7.4, PyQt 5.13.1, Qt 5.13.1, Mutagen 1.42.0, Discid discid 1.2.0, libdiscid 0.6.2, astrcmp C, SSL OpenSSL 1.1.1b 26 Feb 2019

D: 13:43:13,999 tagger.__init__:213: Configuration file path: 'C:/Users/tranq/AppData/Roaming/MusicBrainz/Picard.ini'

D: 13:43:13,999 tagger.__init__:215: User directory: 'C:\\Users\\tranq\\AppData\\Local\\MusicBrainz\\Picard'

D: 13:43:14,031 i18n.setup_gettext:60: unsupported locale setting

D: 13:43:14,031 i18n.setup_gettext:76: Using locale 'en_GB.cp1252'

D: 13:43:14,031 i18n.setup_gettext:78: Loading gettext translation, localedir='C:\\Program Files\\MusicBrainz Picard\\locale'

D: 13:43:14,046 i18n.setup_gettext:82: Loading gettext translation (picard-countries), localedir='C:\\Program Files\\MusicBrainz Picard\\locale'

D: 13:43:14,046 i18n.setup_gettext:85: Loading gettext translation (picard-attributes), localedir='C:\\Program Files\\MusicBrainz Picard\\locale'

D: 13:43:14,046 i18n.setup_gettext:108: _ = <bound method GNUTranslations.gettext of <gettext.GNUTranslations object at 0x0000024931347908>>

D: 13:43:14,046 i18n.setup_gettext:109: N_ = <function <lambda> at 0x0000024930E61D38>

D: 13:43:14,046 i18n.setup_gettext:110: ngettext = <bound method GNUTranslations.ngettext of <gettext.GNUTranslations object at 0x0000024931347908>>

D: 13:43:14,046 i18n.setup_gettext:111: gettext_countries = <bound method GNUTranslations.gettext of <gettext.GNUTranslations object at 0x000002493137BD48>>

D: 13:43:14,046 i18n.setup_gettext:112: gettext_attributes = <bound method GNUTranslations.gettext of <gettext.GNUTranslations object at 0x000002493137CF88>>

D: 13:43:14,062 webservice.set_cache:297: NetworkDiskCache dir: 'C:/Users/tranq/AppData/Local/MusicBrainz/Picard/cache/picard/' size: 42611 / 104857600

I: 13:43:14,062 pluginmanager.load_plugins_from_directory:198: Plugin directory 'C:\\Program Files\\MusicBrainz Picard\\plugins' doesn't exist

D: 13:43:14,062 pluginmanager.load_plugins_from_directory:212: Looking for plugins in directory 'C:\\Users\\tranq\\AppData\\Local\\MusicBrainz\\Picard\\plugins', 1 names found

D: 13:43:14,077 plugin.register:54: ExtensionPoint: track_metadata_processors register <- plugin='abbreviate_artistsort' item=<function abbreviate_artistsort at 0x000002493138B4C8>

D: 13:43:14,077 pluginmanager._load_plugin_from_directory:269: Loading plugin 'Abbreviate artist-sort' version 0.4, compatible with API: 2.0

D: 13:43:14,077 ui.playertoolbar.__init__:83: Internal player: QtMultimedia available, initializing QMediaPlayer

D: 13:43:14,153 ui.playertoolbar.__init__:90: Internal player: available, QMediaPlayer set up

D: 13:43:14,813 tagger.main:913: Looking for Qt locale en_GB in C:/Program Files/MusicBrainz Picard/PyQt5/Qt/translations

D: 13:43:14,820 browser.browser.start:69: Starting the browser integration (127.0.0.1:8000)

D: 13:43:14,917 ui.mainwindow.auto_update_check:1195: Skipping start-up check for program updates. Today: 2019-10-17, Last check: 2019-10-16 (Check interval: 7 days), Update level: 0 (stable)

D: 13:43:42,785 coverart.providers.cover_art_providers:96: CA Providers order: Cover Art Archive [x] > Whitelist [x] > CaaReleaseGroup [ ] > Local Files [ ]

D: 13:43:42,984 webservice.ratecontrol.get_delay_to_next_request:110: ('picard.musicbrainz.org', 443): First request

D: 13:43:42,984 webservice.ratecontrol.increment_requests:135: ('picard.musicbrainz.org', 443): Incrementing requests to: 1

D: 13:43:43,686 webservice.ratecontrol.decrement_requests:143: ('picard.musicbrainz.org', 443): Decrementing requests to: 0

D: 13:43:43,687 webservice._handle_reply:414: Received reply for https://picard.musicbrainz.org:443/api/v2/plugins/: HTTP 200 (OK)

D: 13:43:43,827 webservice.ratecontrol._out_of_backoff:226: ('picard.musicbrainz.org', 443): oobackoff; delay: 1000ms -> 1000ms; slow start; window size 1.000



-> 2.000

D: 13:43:59,877 pluginmanager._install_plugin_file:357: Plugin (file) saved to 'C:\\Users\\tranq\\AppData\\Local\\MusicBrainz\\Picard\\plugins\\lastfmng.zip'

E: 13:43:59,916 pluginmanager.plugin_error:175: Plugin 'lastfmng' : Traceback (most recent call last):

File "C:\Users\tranq\AppData\Local\MusicBrainz\Picard\plugins\lastfmng.zip\lastfmng\vendor\configparser.py", line 1135, in _unify_values

sectiondict = self._sections[section]

KeyError: 'global'



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

File "picard\pluginmanager.py", line 258, in _load_plugin_from_directory

File "C:\Users\tranq\AppData\Local\MusicBrainz\Picard\plugins\lastfmng.zip\lastfmng\__init__.py", line 69, in <module>

from .plugin import LastFMTagger

File "<frozen importlib._bootstrap>", line 983, in _find_and_load

File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 668, in _load_unlocked

File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible

File "C:\Users\tranq\AppData\Local\MusicBrainz\Picard\plugins\lastfmng.zip\lastfmng\plugin.py", line 12, in <module>

from . import settings

File "<frozen importlib._bootstrap>", line 983, in _find_and_load

File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 668, in _load_unlocked

File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible

File "C:\Users\tranq\AppData\Local\MusicBrainz\Picard\plugins\lastfmng.zip\lastfmng\settings.py", line 51, in <module>

LASTFM_HOST = config.get('global', 'lastfm_host')

File "C:\Users\tranq\AppData\Local\MusicBrainz\Picard\plugins\lastfmng.zip\lastfmng\vendor\configparser.py", line 778, in get

d = self._unify_values(section, vars)

File "C:\Users\tranq\AppData\Local\MusicBrainz\Picard\plugins\lastfmng.zip\lastfmng\vendor\configparser.py", line 1138, in _unify_values

raise NoSectionError(section)

picard.plugins.lastfmng.vendor.configparser.NoSectionError: No section: 'global'



E: 13:44:03,778 pluginmanager.install_plugin:398: Unable to load plugin 'lastfmng': Failed loading newly installed plugin lastfmng

D: 13:44:03,778 pluginmanager._remove_plugin_files:302: Remove plugin files and dirs : 'lastfmng'

D: 13:44:03,779 pluginmanager._remove_plugin_files:313: Removing file 'C:\\Users\\tranq\\AppData\\Local\\MusicBrainz\\Picard\\plugins\\lastfmng.zip'

And just in case, I tried a zip file of just the contents of the lastfmng directory:


D: 13:48:50,002 pluginmanager._install_plugin_file:357: Plugin (file) saved to 'C:\\Users\\tranq\\AppData\\Local\\MusicBrainz\\Picard\\plugins\\lastfmng.zip'

E: 13:48:50,002 pluginmanager.install_plugin:398: Unable to load plugin 'lastfmng': bad local file header: 'C:\\Users\\tranq\\AppData\\Local\\MusicBrainz\\Picard\\plugins\\lastfmng.zip'

D: 13:48:50,002 pluginmanager._remove_plugin_files:302: Remove plugin files and dirs : 'lastfmng'
D: 13:48:50,003 pluginmanager._remove_plugin_files:313: Removing file 'C:\\Users\\tranq\\AppData\\Local\\MusicBrainz\\Picard\\plugins\\lastfmng.zip'

I’m not sure what is not working...
Thanks again for looking into it.

________________________________

**Comment by fdemmer** [comment]
The plugin does not work from within a zip file (fails to load config as shown in your logs) and the files released via github don't work using the "Install plugin..." button in Picard (folder structure in the zip is not compatible). I can only guess, it previously worked for you because you also had the unzipped `lastfmng` folder. 

Please follow the install instructions in the readme and put _only_ the extracted `lastfmng` folder in Picard's plugin directory: https://github.com/fdemmer/Picard-Last.fm.ng-Plugin#install

**Comment by Moonbase59** [comment]
Works fine for me (Linux Mint 19.2, Picard 2.2.2). As @fdemmer said, of course using an _unpacked_ plugin folder. (Which you’d want to do anyway because there are real great possibilities hidden in `config.ini` :-))

**Comment by fdemmer** [comment]
@tmepost please report back, if your problem is solved!

**Comment by ghost** [comment]
I just tried it this evening and it works well.  I have had the plugin for quite a while and had updated MB without issues even though both zipped and unzipped files were in the plugin directory.  The new version of MB isn’t as forgiving,  I thought I had tried with just the unzipped directory – but guess had not or had done something else that didn’t make it work...  I’m sorry to have bothered you needlessly but am grateful you patiently pointed out what I had done wrong.


________________________________
