### ISSUE TITLE
Hoping that someone can help me with this........

### ISSUE THREAD

**Issue by hiswillbedun** [fdemmer/Picard-Last.fm.ng-Plugin#61]
I hope that someone can help me. I don’t know python coding. I have a library of over 60,000 songs. However, most came from cds with various artists or from soundtracks. Because of the size of the library, it has gotten to the point, that I don’t even remember what I do have or not. So what I would like to do is the following.

I would like to arrange the files in master folder of genre of artist, then in a folder based on decade of year of original release. I want original release and not release of the greatest hits cd or whatever.

Here is an example, “You Give Love a Bad Name” was released in 1986 by the band Bon Jovi and it is genre of Hard Rock.

So I would like to have a genre Hard Rock with a folder 80s in it. Then the file inside 80s would be Bon Jovi-You Give Love a Bad Name.

I don’t care about album name, featuring artist, actual date of release, track number, etc. All I want is when I open folder Hard Rock and see folders for 70s 80s 90s 2000s 2010s I can find files in those folders based on original release date.

I have installed lastfmng. Just can’t figure it all out. Running MusicBrainz 1.4.2 on Ubuntu.

**Comment by RyanThaDude** [comment]
The current version of Last.fm.ng is for Picard 2, but you're running an outdated version. Update your version of Picard.

**Comment by fdemmer** [comment]
Thank you for your comment Ryan! Closing this, since OP is using did not respond again.

It seems to me you just need to use the appropriate tags in the file naming, maybe that helps: https://picard.musicbrainz.org/docs/scripting/
