### ISSUE TITLE
slow processing time

### ISSUE THREAD

**Issue by ghost** [fdemmer/Picard-Last.fm.ng-Plugin#62]
In one example, after I clicked "scan" for one file, the "loading album information" appears immediately, but it is replaced by the actual information about 30 seconds later (on the right panel).

#### Environment and versions

* Operating system: Windows 10
* Picard version: 2.3.1
* Plugin version: v2.0.4

#### How to reproduce the problem
0. install this plugin (unzipped), restart Picard, enable this plugin, restart Picard
1. scan a music
2. wait 30 seconds for the result to be displayed

#### Note
- It happens with a personal last.fm key or the default one.
- It happens on the 10 music I tested
- If I disable this plugin, the processing time comes back to 2-3 seconds.

PS : thank you for your work !

**Comment by fdemmer** [comment]
Thank you for your nice report, complete with log and everything :+1: 

The release/album you are tagging is not small: https://musicbrainz.org/release/4fafe6a2-4f29-4ee7-81eb-838f1252cd4c

The plugin needs to make a lot of requests to the last.fm API (60 to be precise):
- 1 for the album
- 31 in total, for each track
- 28 total, for each artist (some are duplicates)

The plugin uses Picard's `webservice` code to make HTTP requests and they are queued up (only one at time) and rate-controlled (about 1 every 200ms, starting slow with delay of 1s) to not overwhelm servers. If you enable debug logging in "Help - View Error/Degug Log" you can observe that in lines like this one from the `ratecontrol` module:

	D: 10:43:42,567 /usr/lib/picard/picard/webservice/ratecontrol.get_delay_to_next_request:118: ('ws.audioscrobbler.com', 443): Last request was 183 ms ago, waiting 17 ms before starting another one

I tried your album and this is the timing i took from the log:

10:43:29,691 - 0 - start
10:43:29,741 - 0.05 - all request queued
10:43:42,764 - 13s - all requests sent/received, start processing data
10:43:42,790 - 0.03s - finished processing album tags, start processing per track
10:43:55,315 - 12s - finished processing all tracks, all done

13 seconds for 60 HTTP requests gives an average of 216ms per request. That is very good considering the ~200ms delay by the Picard `webservice` code.

In the last step, there are 5 more HTTP requests adding a total delay of ~1sec again. This could be improved with better caching code, but to be honest to me it is not worth the effort for 1 second.

However, the plugin also uses the `webservice` queue to fetch data already cached during the track-processing, which adds unnecessary delay.

I tried to work around that in 1465ccd6925d7d9c54f3876ee7b87a9878452d6e, it seems to work without side-effects and reduces the track-processing to only the previously mentioned _1 second_ for me... can you test [the latest code](https://github.com/fdemmer/Picard-Last.fm.ng-Plugin/archive/master.zip) please?

**Comment by ghost** [comment]
I tried again (unfortunately I lost the track of the previous test) with the new song (Freaks of the album https://musicbrainz.org/release/4fafe6a2-4f29-4ee7-81eb-838f1252cd4c). The test ([log](https://github.com/fdemmer/Picard-Last.fm.ng-Plugin/files/4477392/log.txt)) took 20s, for 24 tracks and 40 artists. So it did improve (I don't understand the logs well enough for precise metrics):

- First test: 27s for 1 + 31 + 28 = 60 request i.e. 450 ms per request.
- Second test: 20s for 1 + 24 + 40 = 65 request i.e. 307 ms. per request.

It is still slow, but it is proportional to the number of tracks in the albums and not with the number of tracks scanned, so I guess it is to be expected.
Thank you for looking into it.
