### ISSUE TITLE
Version 2.9.0b3 - This plugin either no longer works, or takes a really long time to load, when selecting an album.

### ISSUE THREAD

**Issue by Tenome** [fdemmer/Picard-Last.fm.ng-Plugin#70]
If I turn the plugin off and drop an album with metadata attached, it loads immediately. If I turn the plugin on, the album gets stuck on "Loading album information."

Windows 10, Version 2.9.0b3.

Error log.

https://paste.bingner.com/paste/revgy

**Comment by fdemmer** [comment]
please try the latest release and reopen this issue if there are still problems: https://github.com/fdemmer/Picard-Last.fm.ng-Plugin/releases/tag/v2.0.5

**Comment by khaoohs** [comment]
Had the same issue, looks good to me so far.
