### ISSUE TITLE
Plugin not working from Picard daily build #182

### ISSUE THREAD

**Issue by GitrianDK** [fdemmer/Picard-Last.fm.ng-Plugin#8]
I'm running the daily build of Picard and since Build #182 it is just hanging while loading album information. In this build there is a rework of network requests queues and counting which I think could be the main reason. See http://build.oxygene.sk/job/package-picard-win-daily/

**Comment by fdemmer** [comment]
looks like it: https://github.com/musicbrainz/picard/pull/421

**Comment by fdemmer** [comment]
should be fixed in https://github.com/fdemmer/Picard-Last.fm.ng-Plugin/tree/picard-14
did not check compatibility/will wait for stable release before merging into master.

**Comment by GitrianDK** [comment]
Thanks. Tested and this version is working in both stable version and the daily build.
